test1: element.c element.h pile_statique.c pile_statique.h application.c
	gcc -c element.c
	gcc -c pile_statique.c
	gcc -c application.c
	gcc -o test5.out element.o pile_statique.o application.o
	./test5.out
	
clean :
	rm -f prog *.o
	rm -f prog *.out
